# Generated by Django 5.2.16 on 2026-07-20 10:59

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_example_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RECONSTRUCTION', 'Reconstruction'), ('REPAIR', 'Réparation impression'), ('SEGMENTATION_PARTS', 'Segmentation parties/jointures'), ('SEGMENTATION_FACADE', 'Segmentation bâtiment')], max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('DONE', 'Terminé'), ('ERROR', 'Erreur')], default='PENDING', max_length=10)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('owner_email', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('objet', 'Objet'), ('batiment', 'Bâtiment')], default='objet', max_length=10)),
                ('scale_meters_per_unit', models.FloatField(blank=True, null=True)),
                ('owner_email', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(max_length=500, upload_to=api.models.photo_upload_path)),
                ('order', models.PositiveIntegerField(default=0)),
                ('camera_pose', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.project')),
            ],
            options={
                'db_table': 'photos',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=api.models.mesh_upload_path)),
                ('gltf_file', models.FileField(blank=True, max_length=500, null=True, upload_to=api.models.mesh_upload_path)),
                ('version', models.PositiveIntegerField(default=1)),
                ('vertex_count', models.PositiveIntegerField(blank=True, null=True)),
                ('face_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meshes', to='api.job')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meshes', to='api.project')),
            ],
            options={
                'db_table': 'meshes',
                'ordering': ['project', '-version'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.project'),
        ),
    ]
