# Generated by Django 5.2.16 on 2026-07-21 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mesh_is_watertight_mesh_repair_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('face_ids', models.JSONField(default=list)),
                ('color', models.CharField(default='#4a90d9', max_length=7)),
                ('suggested', models.BooleanField(default=False)),
                ('primitive_type', models.CharField(blank=True, choices=[('plane', 'Plan'), ('cylinder', 'Cylindre'), ('sphere', 'Sphère')], max_length=10)),
                ('primitive_params', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mesh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='api.mesh')),
            ],
            options={
                'db_table': 'parts',
                'ordering': ['mesh', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Joint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joint_type', models.CharField(choices=[('revolute', 'Pivot'), ('prismatic', 'Glissière'), ('fixed', 'Fixe')], max_length=10)),
                ('axis_origin', models.JSONField(default=list)),
                ('axis_direction', models.JSONField(default=list)),
                ('limit_min', models.FloatField(blank=True, null=True)),
                ('limit_max', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joints_as_child', to='api.part')),
                ('parent_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joints_as_parent', to='api.part')),
            ],
            options={
                'db_table': 'joints',
                'ordering': ['id'],
            },
        ),
    ]
