# Generated by Django 5.2.16 on 2026-07-22 09:05

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_part_joint'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='region_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='region_map',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=api.models.region_map_upload_path),
        ),
        migrations.AddField(
            model_name='photo',
            name='region_overlay',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=api.models.region_map_upload_path),
        ),
        migrations.CreateModel(
            name='SemanticClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#888888', max_length=7)),
                ('face_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mesh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_classes', to='api.mesh')),
            ],
            options={
                'db_table': 'semantic_classes',
                'ordering': ['mesh', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PhotoLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semantic_class', models.CharField(choices=[('mur', 'Mur'), ('fenetre', 'Fenêtre'), ('porte', 'Porte'), ('toit', 'Toit')], max_length=10)),
                ('region_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='api.photo')),
            ],
            options={
                'db_table': 'photo_labels',
                'ordering': ['photo', 'region_index'],
                'unique_together': {('photo', 'region_index')},
            },
        ),
    ]
