# Generated by Django 5.2.16 on 2026-07-26 11:02

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_photo_region_count_photo_region_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesh',
            name='angular_deflection',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesh',
            name='linear_deflection',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesh',
            name='step_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=api.models.mesh_upload_path),
        ),
        migrations.AddField(
            model_name='project',
            name='assembly_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Brouillon'), ('SOLVED', 'Résolu'), ('ERROR', 'Erreur')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('RECONSTRUCTION', 'Reconstruction'), ('REPAIR', 'Réparation impression'), ('SEGMENTATION_PARTS', 'Segmentation parties/jointures'), ('SEGMENTATION_FACADE', 'Segmentation bâtiment'), ('CAD_BUILD', 'Construction CAO'), ('CAD_ASSEMBLE', 'Assemblage CAO')], max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('objet', 'Objet'), ('batiment', 'Bâtiment'), ('assembly', 'Assemblage')], default='objet', max_length=10),
        ),
        migrations.CreateModel(
            name='CadAssemblyInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('placement', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assembly_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cad_instances', to='api.project')),
                ('source_mesh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cad_instances', to='api.mesh')),
                ('source_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cad_instances_used_in', to='api.project')),
            ],
            options={
                'db_table': 'cad_assembly_instances',
                'ordering': ['assembly_project', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CadAssemblyConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_type', models.CharField(choices=[('COINCIDENT', 'Coïncidence'), ('CONTACT', 'Contact / coplanaire'), ('PARALLEL', 'Parallélisme'), ('CONCENTRIC', 'Concentricité'), ('DISTANCE', 'Distance'), ('ANGLE', 'Angle'), ('FIXED', 'Fixation au monde'), ('GEAR_MESH', 'Engrènement')], max_length=12)),
                ('reference_a', models.JSONField()),
                ('reference_b', models.JSONField(blank=True, null=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assembly_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cad_constraints', to='api.project')),
                ('instance_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints_as_a', to='api.cadassemblyinstance')),
                ('instance_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraints_as_b', to='api.cadassemblyinstance')),
            ],
            options={
                'db_table': 'cad_assembly_constraints',
                'ordering': ['assembly_project', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CadOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('operation_type', models.CharField(choices=[('PRIMITIVE_BOX', 'Primitive : boîte'), ('PRIMITIVE_SPHERE', 'Primitive : sphère'), ('PRIMITIVE_CYLINDER', 'Primitive : cylindre'), ('PRIMITIVE_CONE', 'Primitive : cône'), ('PRIMITIVE_TORUS', 'Primitive : tore'), ('EXTRUDE', 'Extrusion'), ('REVOLVE', 'Révolution'), ('SURFACE_FROM_WIRE', 'Surface depuis un contour'), ('BOOLEAN_UNION', 'Booléen : union'), ('BOOLEAN_CUT', 'Booléen : différence'), ('BOOLEAN_INTERSECT', 'Booléen : intersection'), ('PATTERN_CIRCULAR', 'Répétition circulaire'), ('PATTERN_LINEAR', 'Répétition linéaire'), ('GEAR_TEETH', 'Denture (engrenage)')], max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cad_operations', to='api.project')),
            ],
            options={
                'db_table': 'cad_operations',
                'ordering': ['project', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CadSketch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plane', models.CharField(choices=[('XY', 'XY'), ('XZ', 'XZ'), ('YZ', 'YZ')], default='XY', max_length=2)),
                ('entities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cad_sketches', to='api.project')),
            ],
            options={
                'db_table': 'cad_sketches',
                'ordering': ['project', 'name'],
            },
        ),
    ]
