# Generated by Django 5.2.16 on 2026-07-26 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mesh_angular_deflection_mesh_linear_deflection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_parts', to='api.project'),
        ),
    ]
